# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#uncomment following if you want to change customeize cluster overall configuraiton
#cluster:
#
#  common:
#    clusterid: pai
#
#    # HDFS, zookeeper data path on your cluster machine.
#    data-path: "/datastorage"
#
#    # Enable QoS feature or not. Default value is "true"
#    qos-switch: "true"
#
#    # If your cluster is created by Azure and the machine is rdma enabled.
#    # Set this configuration as  "true", the rdma environment will be set into your container.
#    az-rdma: "false"
#
#
#  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
#  docker-registry:
#
#    # domain/namespace/image-name:tag
#
#    # If resgiry is docker.io, please fill it the same as your username
#    namespace: openpai
#
#    # E.g., gcr.io.
#    # If your registry is at hub.docker, please fill it as docker.io
#    domain: docker.io
#
#    # If the docker registry doesn't require authentication, please comment out username and password
#    #username: your_registry_username
#    #password: your_registry_password
#
#    tag: latest
#
#    # The name of the secret in kubernetes will be created in your cluster
#    # Must be lower case, e.g., regsecret.
#    secret-name: regsecret

#Uncomment following lines if you want to customize yarn
#hadoop-resource-manager:
#  # job log retain time
#  yarn_log_retain_seconds: 2592000
#  # port for yarn exporter
#  yarn_exporter_port: 9459


#Uncomment following lines if you want to customize hdfs
#hadoop-data-node:
#  # storage path for hdfs, support comma-delimited list of directories, eg. /path/to/folder1,/path/to/folder2 ...
#  # if left empty, will use cluster.common.data-path/hdfs/data
#  storage_path:



#uncomment following if you want to change customeize yarn-frameworklauncher
#yarn-frameworklauncher:
#  frameworklauncher-port: 9086


rest-server:
  # secret for signing authentication tokens, e.g., hello
  #jwt-secret: HelloPAI
  # database admin username
  default-pai-admin-username: your_default_pai_admin_username
  # database admin password
  default-pai-admin-password: your_default_pai_admin_password
  # rest server would achieve marketplace template from below configed github repository
  #github-owner: Microsoft
  #github-repository: pai
  #github-path: marketplace
  # Job Debugging Reservation Seconds.
  #debugging-reservation-seconds: 604800

# uncomment following section if you want to customize the port of web portal
# webportal:
#   server-port: 9286

# uncomment following if you want to change customeize grafana
# grafana:
#   port: 3000

# uncomment following if you want to change customeize drivers
#drivers:
#  set-nvidia-runtime: false
#  # You can set drivers version here. If this value is miss, default value will be 384.111
#  # Current supported version list
#  # 384.111
#  # 390.25
#  # 410.73
#  version: "384.111"

# uncomment following if you want node-exporter listen to different port
# node-exporter:
#   port: 9100

# if you want to enable alert manager to send alert email, uncomment following lines and fill
# the right values.
# alert-manager:
#   receiver: your_addr@example.com
#   smtp_url: smtp.office365.com:587
#   smtp_from: alert_sender@example.com
#   smtp_auth_username: alert_sender@example.com
#   smtp_auth_password: password_for_alert_sender
#   port: 9093 # this is optional, you should not write this if you do not want to change the port alert-manager is listening on

# uncomment following if you want to change customeize prometheus
# prometheus:
#   port: 9091
#   # How frequently to scrape targets
#   scrape_interval: 30

# uncomment following section if you want to customize the port of pylon
# pylon:
#  port: 80

# uncomment following section if you want to customize the threshold of cleaner
# cleaner:
#  threshold: 90 
#  interval: 60


# uncomment following section, if you want to customize the authentication solution.
#authentication:
  #OIDC: false

  # If OIDC is set as the value true, you will have to configure the following properties.
  #OIDC-type: AAD
  #
  #AAD:
  #  # If you wanna configure AAD-OIDC for OpenPAI, the following configuration is mandatory.
  #
  #  # Required
  #  identityMetadata: https://login.microsoftonline.com/${tenant_name}.onmicrosoft.com/.well-known/openid-configuration
  #  # or equivalently: https://login.microsoftonline.com/<tenant_guid>/.well-known/openid-configuration
  #  #
  #  # or you can use the common endpoint
  #  # 'https://login.microsoftonline.com/common/.well-known/openid-configuration'
  #  # To use the common endpoint, you have to either set `validateIssuer` to false, or provide the `issuer` value.
  #
  #  # Required, the client ID of your app in AAD
  #  clientID: ${your_client_id}
  #
  #  # Required if `responseType` is 'code', 'id_token code' or 'code id_token'.
  #  # If app key contains '\', replace it with '\\'.
  #  clientSecret: '${your_client_secret}'
  #
  #  # If you wanna configure AAD-OIDC for OpenPAI, the configuration above is mandatory.
  #
  #  # Optional configure, default value is 'code id_token'. And its value must be 'code', 'code id_token', 'id_token code' or 'id_token'
  #  responseType: 'code id_token'
  #
  #  # Optional configure, default value is 'form_post'
  #  responseMode: 'form_post'
  #
  #  # Optional configure, default value is true.
  #  allowHttpForRedirectUrl: true
  #
  #  # Optional configure, default value is true. Configuration to set to false if you don't want to validate issuer
  #  validateIssuer: true
  #
  #  # Optional configure default value is false. Configuration to set to true if you are using B2C endpoint
  #  # This sample is for v1 endpoint only, so we set it to false
  #  isB2C: false
  #
  #  # Optional configure. If you want to provide the issuer(s) you want to validate instead of using the issuer from metadata
  #  issuer: null
  #
  #  # Optional configure default value is false. Configuration to set to true if the `verify` function has 'req' as the first parameter
  #  passReqToCallback: false
  #
  #  # Optional configure, but suggest to configure it. If `useCookieInsteadOfSession` is set to true. You can provide multiple set of key/iv pairs for key
  #  # rollover purpose. We always use the first set of key/iv pair to encrypt cookie, but we will try every set of
  #  # key/iv pair to decrypt cookie. Key can be any string of length 32, and iv can be any string of length 12.
  #  cookieEncryptionKeys:
  #    - key: '12345678901234567890123456789012'
  #      iv: '123456789012'
  #    - key: 'abcdefghijklmnopqrstuvwxyzabcdef'
  #      iv: 'abcdefghijkl'
  #
  #  # Optional. The additional scope you want besides 'openid', for example: ['email', 'profile'].
  #  scope: null
  #
  #  # Optional, 'error', 'warn' or 'info'
  #  loggingLevel: info
  #
  #  # Optional. The lifetime of nonce in session or cookie, the default value is 3600 (seconds).
  #  nonceLifetime: null
  #
  #  # Optional. The max amount of nonce saved in session or cookie, the default value is 10.
  #  nonceMaxAmount: 5
  #
  #  # Optional. The clock skew allowed in token validation, the default value is 300 seconds.
  #  clockSkew: null
  #
  #  # Optional.
  #  # If you want to get access_token for a specific resource, you can provide the resource here; otherwise,
  #  # set the value to null.
  #  # Note that in order to get access_token, the responseType must be 'code', 'code id_token' or 'id_token code'.
  #  resourceURL: 'https://graph.windows.net'